# Generated by Django 3.0.4 on 2020-05-16 20:26

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200331_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
