# Generated by Django 3.0.4 on 2020-06-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_content_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='price',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
