# Generated by Django 3.0.4 on 2020-06-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderproduce_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduce',
            name='content',
        ),
    ]
